### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by kubeworkz** [ITenthusiasm/remix-supertokens#3]
[remix-supertokens.tar.gz](https://github.com/ITenthusiasm/remix-supertokens/files/9694328/remix-supertokens.tar.gz)

Definitely needed SuperTokens for Remix. I'd like to help out. I added prisma/postgresql and tailwindcss. The prisma schema is the Supertokens postgres db schema.

Here's the docker-compose.yaml  used to fire up the backend.
```
version: '3'

services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: supertokens
    ports:
      - 5432:5432
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    depends_on:
      - db
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://postgres:postgres@db:5432/supertokens"
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat 
<&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app_network:
    driver: bridge

volumes:
    pgdata:
```
